steps:

- name: gcr.io/cloud-builders/gcloud
  id: 'A'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo 'A'
    date
    sleep 3
- name: gcr.io/cloud-builders/gcloud
  id: 'B'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo 'B'
    date
    sleep 3
  waitFor:
  - '-'
- name: gcr.io/cloud-builders/gcloud
  id: 'LAST'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo 'LAST'
    date
