steps:

- name: gcr.io/cloud-builders/gcloud
  id: 'A'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo 'A'
- name: gcr.io/cloud-builders/gcloud
  id: 'B'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo 'B'
  waitFor:
  - '-'
- name: gcr.io/cloud-builders/gcloud
  id: 'C'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo 'C'
