steps:

- name: gcr.io/cloud-builders/gcloud
  id: 'A'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo 'A'
    date
    sleep 3
- name: gcr.io/cloud-builders/gcloud
  id: 'B'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo 'B'
    date
    sleep 3
  waitFor:
  - '-'
- name: gcr.io/cloud-builders/gcloud
  id: 'C'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo 'C'
    date
    sleep 3
  waitFor:
  - '-'
- name: gcr.io/cloud-builders/gcloud
  id: 'D'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo 'D'
    date
    sleep 3
  waitFor:
  - '-'
- name: gcr.io/cloud-builders/gcloud
  id: 'E'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo 'D'
    date
    sleep 3
  waitFor:
  - '-'
- name: gcr.io/cloud-builders/gcloud
  id: 'F'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo 'D'
    date
    sleep 3
  waitFor:
  - '-'
- name: gcr.io/cloud-builders/gcloud
  id: 'G'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo 'D'
    date
    sleep 3
  waitFor:
  - '-'
- name: gcr.io/cloud-builders/gcloud
  id: 'H'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo 'D'
    date
    sleep 3
  waitFor:
  - '-'
- name: gcr.io/cloud-builders/gcloud
  id: 'I'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo 'D'
    date
    sleep 3
  waitFor:
  - '-'
- name: gcr.io/cloud-builders/gcloud
  id: 'LAST'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo 'LAST'
    date
