apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rails-docker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: rails
    spec:
      containers:
        - image: gcr.io/${PROJECT_ID}/${IMAGE_RAILS}:${TAG}
          name: rails
          ports:
            - containerPort: 9292
          command: ["bundle", "exec", "rails", "s", "puma", "-b", "0.0.0.0", "-p", "9292", "-e", "development"]
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials-password
                key: password
        - image: gcr.io/${PROJECT_ID}/${IMAGE_RAILS}:${TAG}
          name: sidekiq
          command: ["bundle", "exec", "sidekiq"]
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials-password
                key: password
        - image: gcr.io/cloudsql-docker/gce-proxy:1.09
          name: cloudsql-proxy
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=${INSTANCE_CONNECTION_NAME}=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
        - image: redis:3.2
          name: redis
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
