apiVersion: v1
kind: Service
metadata:
  name: raysci
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: "80"
    targetPort: 9292
  - port: 9292
    name: rails
  selector:
    application: rails
